# Anything put here will be loaded for all games,
# alongside the game's config or default.ini depending on your preference.
hotkey_add_virtual_user = f5
hotkey_capture_frame = f12
hotkey_emulator_settings = f3
hotkey_fullscreen = f11
hotkey_pause = f9
hotkey_quit = lctrl, lshift, end
hotkey_reload_inputs = f8
hotkey_remove_virtual_user = f4
hotkey_screenshot_with_overlays = lalt, f12
hotkey_show_fps = f10
hotkey_toggle_mouse_to_gyro = f6
hotkey_toggle_mouse_to_joystick = f7
hotkey_toggle_mouse_to_touchpad = delete
hotkey_volume_down = kpminus
hotkey_volume_up = kpplus
